apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 80
  selector:
    service: frontend
  type: LoadBalancer
